
CREATE TABLE users(
	ID INTEGER AUTO_INCREMENT,
	NAME varchar(14),
	COUNTER_POSTS Integer,
	DATE_JOINED timestamp,
	PRIMARY KEY (ID)
);

CREATE TABLE posts(
	POST_ID INTEGER AUTO_INCREMENT,
	POST_CONTENT varchar(777),
	POST_DATE timestamp,
	POST_TYPE varchar(20),
	USER_ID INTEGER,
	PRIMARY KEY (POST_ID)
);

ALTER TABLE posts ADD CONSTRAINT fk_post_user FOREIGN KEY (USER_ID) REFERENCES users(ID);

INSERT INTO users(NAME, COUNTER_POSTS, DATE_JOINED) VALUES ("Valeria", 0, current_date())
INSERT INTO users(NAME, COUNTER_POSTS, DATE_JOINED) VALUES ("Joseph", 0, current_date())
INSERT INTO users(NAME, COUNTER_POSTS, DATE_JOINED) VALUES ("Aron", 0, current_date())
INSERT INTO users(NAME, COUNTER_POSTS, DATE_JOINED) VALUES ("Rachel", 0, current_date())


INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("FIRST POST, SO EXCITED!!", current_date(), "PERSONAL", "1");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("FIRST POST, SO EXCITED!!", current_date(), "PERSONAL", "2");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("FIRST POST, SO EXCITED!!", current_date(), "PERSONAL", "3");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("FIRST POST, SO EXCITED!!", current_date(), "PERSONAL", "4");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("SECOND POST, SO EXCITED!!", current_date(), "PERSONAL", "1");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("THIRD POST, SO EXCITED!!", current_date(), "PERSONAL", "1");
INSERT INTO posts (POST_CONTENT, POST_DATE, POST_TYPE, USER_ID) VALUES ("FOURTH POST, SO EXCITED!!", current_date(), "PERSONAL", "1");