
CREATE TABLE users(
	ID INTEGER AUTO_INCREMENT,
	NAME varchar(14),
	COUNTER_POSTS Integer,
	DATE_JOINED timestamp,
	PRIMARY KEY (ID)
);

CREATE TABLE posts(
	POST_ID INTEGER AUTO_INCREMENT,
	POST_CONTENT varchar(777),
	POST_DATE timestamp,
	POST_TYPE varchar(20),
	USER_ID INTEGER,
	PRIMARY KEY (POST_ID)
);

ALTER TABLE posts ADD CONSTRAINT fk_post_user FOREIGN KEY (USER_ID) REFERENCES users(ID);